//Geo JSON data for marker locations
const chinatownsdata = [
  {
    "Name": "Manhattan Chinatown",
    "longitude": -73.996895,
    "latitude": 40.716474,
    "City": "New York City",
    "Country": "United States of America",
    "Year": "1870s",
    "Century": "19th Century",
    "Population over 10000?": "Yes",
    "Majority Chinese or Asian population?": "No*",
    "Paifang?": "No"
  },
  {
    "Name": "Flushing Chinatown",
    "longitude": -73.829419,
    "latitude": 40.758017,
    "City": "New York City",
    "Country": "United States of America",
    "Year": "1970s ",
    "Century": "20th Century",
    "Population over 10000?": "Yes",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "No"
  },
  {
    "Name": "Sunset Park Chinatown",
    "longitude": -74.005717,
    "latitude": 40.639353,
    "City": "New York City",
    "Country": "United States of America",
    "Year": "1980s  ",
    "Century": "20th Century",
    "Population over 10000?": "Yes",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "Yes"
  },
  {
    "Name": "Boston Chinatown",
    "longitude": -71.061645,
    "latitude": 42.349707,
    "City": "Boston",
    "Country": "United States of America",
    "Year": "1874",
    "Century": "19th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "Yes"
  },
  {
    "Name": "Chicago Chinatown",
    "longitude": -87.634064,
    "latitude": 41.85049,
    "City": "Chicago",
    "Country": "United States of America",
    "Year": "1870s ",
    "Century": "19th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "Yes"
  },
  {
    "Name": "Honolulu Chinatown Historic District",
    "longitude": -157.862925,
    "latitude": 21.312281,
    "City": "Honolulu",
    "Country": "United States of America",
    "Year": "1850s",
    "Century": "19th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "No",
    "Paifang?": "Yes"
  },
  {
    "Name": "Houston Chinatown",
    "longitude": -95.545204,
    "latitude": 29.70505,
    "City": "Houston",
    "Country": "United States of America",
    "Year": "1983",
    "Century": "20th Century",
    "Population over 10000?": "Yes",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "Yes"
  },
  {
    "Name": "Los Angeles Chinatown",
    "longitude": -118.23651,
    "latitude": 34.061636,
    "City": "Los Angeles",
    "Country": "United States of America",
    "Year": "1938",
    "Century": "20th Century",
    "Population over 10000?": "Yes",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "Yes"
  },
  {
    "Name": "Philadelphia Chinatown",
    "longitude": -75.157492,
    "latitude": 39.955572,
    "City": "Philadelphia",
    "Country": "United States of America",
    "Year": "1870s ",
    "Century": "19th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "No",
    "Paifang?": "Yes"
  },
  {
    "Name": "Old Town Chinatown",
    "longitude": -122.674512,
    "latitude": 45.526003,
    "City": "Portland",
    "Country": "United States of America",
    "Year": "1905",
    "Century": "20th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "No",
    "Paifang?": "Yes"
  },
  {
    "Name": "San Francisco Chinatown",
    "longitude": -122.406337,
    "latitude": 37.794263,
    "City": "San Francisco",
    "Country": "United States of America",
    "Year": "1848",
    "Century": "19th Century",
    "Population over 10000?": "Yes",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "Yes"
  },
  {
    "Name": "Oakland Chinatown",
    "longitude": -122.269457,
    "latitude": 37.79943,
    "City": "Oakland",
    "Country": "United States of America",
    "Year": "1850s",
    "Century": "19th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "No"
  },
  {
    "Name": "Seattle Chinatown-International District",
    "longitude": -122.324525,
    "latitude": 47.597536,
    "City": "Seattle",
    "Country": "United States of America",
    "Year": "1900s",
    "Century": "20th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "No",
    "Paifang?": "Yes"
  },
  {
    "Name": "Washington D.C. Chinatown",
    "longitude": -77.020966,
    "latitude": 38.900456,
    "City": "Washington D.C.",
    "Country": "United States of America",
    "Year": "1930s ",
    "Century": "20th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "No",
    "Paifang?": "Yes"
  },
  {
    "Name": "Calgary Chinatown",
    "longitude": -114.065,
    "latitude": 51.050833,
    "City": "Calgary",
    "Country": "Canada",
    "Year": "1880s",
    "Century": "19th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "Yes"
  },
  {
    "Name": "Edmonton Chinatown",
    "longitude": -113.487,
    "latitude": 53.555,
    "City": "Edmonton",
    "Country": "Canada",
    "Year": "1900s",
    "Century": "20th Century",
    "Population over 10000?": "No Available Data",
    "Majority Chinese or Asian population?": "No Available Data",
    "Paifang?": "Yes"
  },
  {
    "Name": "Quartier Chinois",
    "longitude": -73.5608,
    "latitude": 45.50759,
    "City": "Montreal",
    "Country": "Canada",
    "Year": "1890s",
    "Century": "19th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "No Available Data",
    "Paifang?": "Yes"
  },
  {
    "Name": "Ottawa Chinatown",
    "longitude": -75.70721,
    "latitude": 45.41084,
    "City": "Ottawa",
    "Country": "Canada",
    "Year": "1931",
    "Century": "20th Century",
    "Population over 10000?": "Yes",
    "Majority Chinese or Asian population?": "No Available Data",
    "Paifang?": "Yes"
  },
  {
    "Name": "Downtown Chinatown",
    "longitude": -79.398,
    "latitude": 43.6529,
    "City": "Toronto",
    "Country": "Canada",
    "Year": "1950s",
    "Century": "20th Century",
    "Population over 10000?": "Yes",
    "Majority Chinese or Asian population?": "No",
    "Paifang?": "No"
  },
  {
    "Name": "Vancouver Chinatown",
    "longitude": -123.099444,
    "latitude": 49.28,
    "City": "Vancouver",
    "Country": "Canada",
    "Year": "1885",
    "Century": "19th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "No",
    "Paifang?": "Yes"
  },
  {
    "Name": "Victoria Chinatown",
    "longitude": -123.367224,
    "latitude": 48.429391,
    "City": "Victoria",
    "Country": "Canada",
    "Year": "1858",
    "Century": "19th Century",
    "Population over 10000?": "No Available Data",
    "Majority Chinese or Asian population?": "No Available Data",
    "Paifang?": "Yes"
  },
  {
    "Name": "Windsor Chinatown",
    "longitude": -83,
    "latitude": 42.301,
    "City": "Windsor",
    "Country": "Canada",
    "Year": "1961",
    "Century": "20th Century",
    "Population over 10000?": "No Available Data",
    "Majority Chinese or Asian population?": "No Available Data",
    "Paifang?": "No"
  },
  {
    "Name": "Winnipeg Chinatown",
    "longitude": -97.138403,
    "latitude": 49.901618,
    "City": "Winnipeg",
    "Country": "Canada",
    "Year": "1910s",
    "Century": "20th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "Yes",
    "Paifang?": "Yes"
  },
  {
    "Name": "Buenos Aires Barrio Chino",
    "longitude": -58.45,
    "latitude": -34.557778,
    "City": "Buenos Aires",
    "Country": "Argentina",
    "Year": "1980s  ",
    "Century": "20th Century",
    "Population over 10000?": "No",
    "Majority Chinese or Asian population?": "No",
    "Paifang?": "Yes"
  },
  {
    "Name": "La Chinesca",
    "longitude": -115.493668,
    "latitude": 32.662803,
    "City": "Mexicali",
    "Country": "Mexico",
    "Year": "1918",
    "Century": "20th Century",
    "Population over 10000?": "Yes",
    "Majority Chinese or Asian population?": "No Available Data",
    "Paifang?": "Yes"
  },
  {
    "Name": "Mexico City Barrio Chino ",
    "longitude": -99.1427,
    "latitude": 19.432,
    "City": "Mexico City",
    "Country": "Mexico",
    "Year": "1900s",
    "Century": "20th Century",
    "Population over 10000?": "No Available Data",
    "Majority Chinese or Asian population?": "No Available Data",
    "Paifang?": "Yes"
  },
  {
   "Name": "Adelaide Chinatown",
   "longitude": 138.5958964,
   "latitude": -34.92940737,
   "City": "Adelaide",
   "Country": "Australia",
   "Year": "1970s ",
   "Century": "",
   "Population over 10000?": "No Available Data",
   "Majority Chinese or Asian population?": "No Available Data",
   "Paifang?": "Yes"
 },
 {
   "Name": "Brisbane Chinatown",
   "longitude": 153.0337285,
   "latitude": -27.458515246942568,
   "City": "Brisbane",
   "Country": "Australia",
   "Year": "1980s  ",
   "Century": "",
   "Population over 10000?": "No Available Data",
   "Majority Chinese or Asian population?": "No Available Data",
   "Paifang?": "Yes"
 },
 {
   "Name": "Gold Coast Chinatown",
   "longitude": 153.413474,
   "latitude": -27.96870554,
   "City": "Gold Coast",
   "Country": "Australia",
   "Year": "2014",
   "Century": "",
   "Population over 10000?": "No*",
   "Majority Chinese or Asian population?": "No Available Data",
   "Paifang?": "Yes"
 },
 {
   "Name": "Melbourne Chinatown",
   "longitude": 144.9668251,
   "latitude": -37.81187035,
   "City": "Melbourne",
   "Country": "Australia",
   "Year": "1850s",
   "Century": "",
   "Population over 10000?": "No*",
   "Majority Chinese or Asian population?": "No Available Data",
   "Paifang?": "Yes"
 },
 {
   "Name": "Perth Chinatown",
   "longitude": 115.857276,
   "latitude": -31.949021,
   "City": "Perth",
   "Country": "Australia",
   "Year": "1980s  ",
   "Century": "",
   "Population over 10000?": "No Available Data",
   "Majority Chinese or Asian population?": "No Available Data",
   "Paifang?": "Yes"
 },
 {
   "Name": "Sydney Chinatown",
   "longitude": 151.205746,
   "latitude": -33.87864859,
   "City": "Sydney",
   "Country": "Australia",
   "Year": "1920s",
   "Century": "",
   "Population over 10000?": "Yes",
   "Majority Chinese or Asian population?": "Yes",
   "Paifang?": "Yes"
 }
]