//Geo JSON data for marker locations
const chinatownsdata = [
 {
   "Name": "Manhattan Chinatown",
   "longitude": -73.996895,
   "latitude": 40.716474,
   "City": "New York City",
   "Country": "United States of America",
   "Year": "1870s",
   "Century": "19th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Flushing Chinatown",
   "longitude": -73.829419,
   "latitude": 40.758017,
   "City": "New York City",
   "Country": "United States of America",
   "Year": "1970s ",
   "Century": "20th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Fujian; Zhejiang"
 },
 {
   "Name": "Sunset Park Chinatown",
   "longitude": -74.005717,
   "latitude": 40.639353,
   "City": "New York City",
   "Country": "United States of America",
   "Year": "1980s  ",
   "Century": "20th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Fujian"
 },
 {
   "Name": "Boston Chinatown",
   "longitude": -71.061645,
   "latitude": 42.349707,
   "City": "Boston",
   "Country": "United States of America",
   "Year": "1874",
   "Century": "19th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Chicago Chinatown",
   "longitude": -87.634064,
   "latitude": 41.85049,
   "City": "Chicago",
   "Country": "United States of America",
   "Year": "1870s ",
   "Century": "19th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Honolulu Chinatown Historic District",
   "longitude": -157.862925,
   "latitude": 21.312281,
   "City": "Honolulu",
   "Country": "United States of America",
   "Year": "1850s",
   "Century": "19th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Houston Chinatown",
   "longitude": -95.545204,
   "latitude": 29.70505,
   "City": "Houston",
   "Country": "United States of America",
   "Year": "1983",
   "Century": "20th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Insufficient information"
 },
 {
   "Name": "Los Angeles Chinatown",
   "longitude": -118.23651,
   "latitude": 34.061636,
   "City": "Los Angeles",
   "Country": "United States of America",
   "Year": "1938",
   "Century": "20th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Philadelphia Chinatown",
   "longitude": -75.157492,
   "latitude": 39.955572,
   "City": "Philadelphia",
   "Country": "United States of America",
   "Year": "1870s ",
   "Century": "19th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Old Town Chinatown",
   "longitude": -122.674512,
   "latitude": 45.526003,
   "City": "Portland",
   "Country": "United States of America",
   "Year": "1905",
   "Century": "20th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "San Francisco Chinatown",
   "longitude": -122.406337,
   "latitude": 37.794263,
   "City": "San Francisco",
   "Country": "United States of America",
   "Year": "1848",
   "Century": "19th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Oakland Chinatown",
   "longitude": -122.269457,
   "latitude": 37.79943,
   "City": "Oakland",
   "Country": "United States of America",
   "Year": "1850s",
   "Century": "19th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Seattle Chinatown-International District",
   "longitude": -122.324525,
   "latitude": 47.597536,
   "City": "Seattle",
   "Country": "United States of America",
   "Year": "1900s",
   "Century": "20th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Washington D.C. Chinatown",
   "longitude": -77.020966,
   "latitude": 38.900456,
   "City": "Washington D.C.",
   "Country": "United States of America",
   "Year": "1930s ",
   "Century": "20th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Calgary Chinatown",
   "longitude": -114.065,
   "latitude": 51.050833,
   "City": "Calgary",
   "Country": "Canada",
   "Year": "1880s",
   "Century": "19th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Edmonton Chinatown",
   "longitude": -113.487,
   "latitude": 53.555,
   "City": "Edmonton",
   "Country": "Canada",
   "Year": "1900s",
   "Century": "20th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Quartier Chinois",
   "longitude": -73.5608,
   "latitude": 45.50759,
   "City": "Montreal",
   "Country": "Canada",
   "Year": "1890s",
   "Century": "19th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Ottawa Chinatown",
   "longitude": -75.70721,
   "latitude": 45.41084,
   "City": "Ottawa",
   "Country": "Canada",
   "Year": "1931",
   "Century": "20th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Downtown Chinatown",
   "longitude": -79.398,
   "latitude": 43.6529,
   "City": "Toronto",
   "Country": "Canada",
   "Year": "1960s",
   "Century": "20th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Vancouver Chinatown",
   "longitude": -123.099444,
   "latitude": 49.28,
   "City": "Vancouver",
   "Country": "Canada",
   "Year": "1885",
   "Century": "19th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Victoria Chinatown",
   "longitude": -123.367224,
   "latitude": 48.429391,
   "City": "Victoria",
   "Country": "Canada",
   "Year": "1858",
   "Century": "19th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Windsor Chinatown",
   "longitude": -83,
   "latitude": 42.301,
   "City": "Windsor",
   "Country": "Canada",
   "Year": "1961",
   "Century": "20th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Winnipeg Chinatown",
   "longitude": -97.138403,
   "latitude": 49.901618,
   "City": "Winnipeg",
   "Country": "Canada",
   "Year": "1910s",
   "Century": "20th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Buenos Aires Barrio Chino",
   "longitude": -58.45,
   "latitude": -34.557778,
   "City": "Buenos Aires",
   "Country": "Argentina",
   "Year": "1980s  ",
   "Century": "20th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Fujian"
 },
 {
   "Name": "La Chinesca",
   "longitude": -115.493668,
   "latitude": 32.662803,
   "City": "Mexicali",
   "Country": "Mexico",
   "Year": "1918",
   "Century": "20th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Mexico City Barrio Chino ",
   "longitude": -99.1427,
   "latitude": 19.432,
   "City": "Mexico City",
   "Country": "Mexico",
   "Year": "1900s",
   "Century": "20th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Honiara Chinatown",
   "longitude": 159.966397,
   "latitude": -9.437953,
   "City": "Honiara",
   "Country": "Solomon Islands",
   "Year": "1940s",
   "Century": "20th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Adelaide Chinatown",
   "longitude": 138.5958964,
   "latitude": -34.92940737,
   "City": "Adelaide",
   "Country": "Australia",
   "Year": "1970s",
   "Century": "20th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Vietnam*"
 },
 {
   "Name": "Brisbane Chinatown",
   "longitude": 153.0337285,
   "latitude": -27.45851525,
   "City": "Brisbane",
   "Country": "Australia",
   "Year": "1980s",
   "Century": "20th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Gold Coast Chinatown",
   "longitude": 153.413474,
   "latitude": -27.96870554,
   "City": "Gold Coast",
   "Country": "Australia",
   "Year": "2014",
   "Century": "21st Century",
   "Population over 10000?": "No*",
   "Major regional sources of original Chinatown residents": "Insufficient information"
 },
 {
   "Name": "Melbourne Chinatown",
   "longitude": 144.9668251,
   "latitude": -37.81187035,
   "City": "Melbourne",
   "Country": "Australia",
   "Year": "1850s",
   "Century": "19th Century",
   "Population over 10000?": "No*",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Perth Chinatown",
   "longitude": 115.857276,
   "latitude": -31.949021,
   "City": "Perth",
   "Country": "Australia",
   "Year": "1980s",
   "Century": "20th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Sydney Chinatown",
   "longitude": 151.205746,
   "latitude": -33.87864859,
   "City": "Sydney",
   "Country": "Australia",
   "Year": "1920s",
   "Century": "20th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Tiriti Bazaar টিরিটি বাজার",
   "longitude": 88.355,
   "latitude": 22.573889,
   "City": "Kolkata",
   "Country": "India",
   "Year": "1790s",
   "Century": "18th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Hakka"
 },
 {
   "Name": "Glodok",
   "longitude": 106.8164227,
   "latitude": -6.141673127,
   "City": "Jakarta",
   "Country": "Indonesia",
   "Year": "1740",
   "Century": "18th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Guangdong; Fujian"
 },
 {
   "Name": "Nankin-machi 南京町",
   "longitude": 135.188056,
   "latitude": 34.688056,
   "City": "Kobe",
   "Country": "Japan",
   "Year": "1868",
   "Century": "19th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Jiangsu"
 },
 {
   "Name": "Nagasaki Shinchi Chinatown 長崎新地中華街",
   "longitude": 129.875833,
   "latitude": 32.741944,
   "City": "Nagasaki",
   "Country": "Japan",
   "Year": "1700s",
   "Century": "18th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Fujian"
 },
 {
   "Name": "Yokohama Chinatown 横浜中華街",
   "longitude": 139.6447867,
   "latitude": 35.44329808,
   "City": "Yokohama",
   "Country": "Japan",
   "Year": "1859",
   "Century": "19th Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Guangdong; Shanghai"
 },
 {
   "Name": "Petaling Street",
   "longitude": 101.6977247,
   "latitude": 3.144641492,
   "City": "Kuala Lumpur",
   "Country": "Malaysia",
   "Year": "1870s",
   "Century": "19th Century",
   "Population over 10000?": "No*",
   "Major regional sources of original Chinatown residents": "Guangdong; Fujian; Hakka"
 },
 {
   "Name": "Kampung Cina",
   "longitude": 103.132849,
   "latitude": 5.333428115,
   "City": "Kuala Terengganu",
   "Country": "Malaysia",
   "Year": "16th century",
   "Century": "17th Century",
   "Population over 10000?": "No*",
   "Major regional sources of original Chinatown residents": "Fujian"
 },
 {
   "Name": "Kuching Chinatown",
   "longitude": 110.3491521,
   "latitude": 1.561787222,
   "City": "Kuching",
   "Country": "Malaysia",
   "Year": "Mid-to-late 19th century",
   "Century": "19th Century",
   "Population over 10000?": "No*",
   "Major regional sources of original Chinatown residents": "Fujian; Guangdong; Hainan"
 },
 {
   "Name": "Jonker Walk",
   "longitude": 102.246528,
   "latitude": 2.196722,
   "City": "Malacca City",
   "Country": "Malaysia",
   "Year": "Early 18th century",
   "Century": "18th Century",
   "Population over 10000?": "No*",
   "Major regional sources of original Chinatown residents": "Fujian"
 },
 {
   "Name": "Yangon Chinatown ရန်ကုန် တရုတ်တန်း",
   "longitude": 96.151254,
   "latitude": 16.773339,
   "City": "Yangon",
   "Country": "Myanmar",
   "Year": "1850s",
   "Century": "19th Century",
   "Population over 10000?": "No*",
   "Major regional sources of original Chinatown residents": "Guangdong; Fujian"
 },
 {
   "Name": "Binondo",
   "longitude": 120.9767669,
   "latitude": 14.59802304,
   "City": "Manila",
   "Country": "Philippines",
   "Year": "1594",
   "Century": "16th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Fujian"
 },
 {
   "Name": "Davao Chinatown, Lungsod Tsina sa Dabaw",
   "longitude": 125.6272513,
   "latitude": 7.079340975,
   "City": "Davao",
   "Country": "Philippines",
   "Year": "2004",
   "Century": "21st Century",
   "Population over 10000?": "No Available Data",
   "Major regional sources of original Chinatown residents": "Fujian"
 },
 {
   "Name": "Singapore Chinatown",
   "longitude": 103.8448509,
   "latitude": 1.281491464,
   "City": "Singapore",
   "Country": "Singapore",
   "Year": "1820s",
   "Century": "19th Century",
   "Population over 10000?": "No",
   "Major regional sources of original Chinatown residents": "Guangdong; Fujian; Hakka"
 },
 {
   "Name": "Incheon Chinatown 인천차이나타운",
   "longitude": 126.6181,
   "latitude": 37.4763,
   "City": "Incheon",
   "Country": "Singapore",
   "Year": "1884",
   "Century": "19th Century",
   "Population over 10000?": "No*",
   "Major regional sources of original Chinatown residents": "Shandong"
 },
 {
   "Name": "Bangkok Chinatown ไชนาทาวน์",
   "longitude": 100.5103488,
   "latitude": 13.7403018,
   "City": "Bangkok",
   "Country": "Thailand",
   "Year": "1860s",
   "Century": "19th Century",
   "Population over 10000?": "Yes",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Chợ Lớn",
   "longitude": 106.6576545,
   "latitude": 10.75576097,
   "City": "Ho Chi Minh City",
   "Country": "Vietnam",
   "Year": "1770s",
   "Century": "18th Century",
   "Population over 10000?": "Yes*",
   "Major regional sources of original Chinatown residents": "Guangdong; Fujian; Hainan; Hakka"
 },
 {
   "Name": "Van Wesenbekestraat",
   "longitude": 4.420765321,
   "latitude": 51.22006028,
   "City": "Antwerp",
   "Country": "Belgium",
   "Year": "",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Chinatown Milan",
   "longitude": 9.177225,
   "latitude": 45.481529,
   "City": "Milan",
   "Country": "Italy",
   "Year": "1920s",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Zhejiang"
 },
 {
   "Name": "Quartier Asiatique",
   "longitude": 2.362546662,
   "latitude": 48.82380128,
   "City": "Paris",
   "Country": "France",
   "Year": "1980s  ",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Vietnam*"
 },
 {
   "Name": "Zeedijk",
   "longitude": 4.900289787,
   "latitude": 52.37392953,
   "City": "Amsterdam",
   "Country": "Netherlands",
   "Year": "1911",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "The Hague's Chinatown",
   "longitude": 4.315620583,
   "latitude": 52.07523695,
   "City": "The Hague",
   "Country": "Netherlands",
   "Year": "1970s ",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Usera",
   "longitude": -3.706115,
   "latitude": 40.384455,
   "City": "Madrid",
   "Country": "Spain",
   "Year": "2000s",
   "Century": "21st Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Zhejiang"
 },
 {
   "Name": "Birmingham Chinatown",
   "longitude": -1.897275,
   "latitude": 52.474489,
   "City": "Birmingham",
   "Country": "England",
   "Year": "1960s",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Hong Kong"
 },
 {
   "Name": "Liverpool Chinatown",
   "longitude": -2.97712428,
   "latitude": 53.39968917,
   "City": "Liverpool",
   "Country": "England",
   "Year": "1890s",
   "Century": "19th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Guangdong; Shanghai"
 },
 {
   "Name": "London Chinatown",
   "longitude": -0.13085326,
   "latitude": 51.5127155,
   "City": "London",
   "Country": "England",
   "Year": "1970s ",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Hong Kong"
 },
 {
   "Name": "Manchester Chinatown",
   "longitude": -2.240590923,
   "latitude": 53.47871387,
   "City": "Manchester",
   "Country": "England",
   "Year": "1950s",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Hong Kong"
 },
 {
   "Name": "Newcastle Chinatown",
   "longitude": -1.620100919,
   "latitude": 54.9723168,
   "City": "Newcastler",
   "Country": "England",
   "Year": "1970s ",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Hong Kong"
 },
 {
   "Name": "Barrio Chino Lima",
   "longitude": -77.025134,
   "latitude": -12.05232,
   "City": "Lima",
   "Country": "Peru",
   "Year": "1860s",
   "Century": "19th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Commissioner Street",
   "longitude": 28.0529268,
   "latitude": -26.20395729,
   "City": "Johannesburg",
   "Country": "South Africa",
   "Year": "1900s",
   "Century": "20th Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Guangdong"
 },
 {
   "Name": "Cyrildene",
   "longitude": 28.10171835,
   "latitude": -26.17475346,
   "City": "Johannesberg",
   "Country": "South Africa",
   "Year": "2000s",
   "Century": "21st Century",
   "Population over 10000?": "",
   "Major regional sources of original Chinatown residents": "Fujian"
 }
]
